#!/usr/bin/env bash

# heroku will override $PS1 when specified as a config var, so we'll set it here to make the jupyter
# terminal interface a little prettier:
export PS1='\[\033[01;34m\]\w\[\033[00m\]\$'

echo "Archiving proxy server files for blob for proxy build..."
tar -czf proxy_server_app.tar.gz proxy_server/*
echo "Blob created"

echo "Creating app for proxy server..."
python3 create_proxy.py
echo "Proxy server app created"


echo "Starting Jupyterhub..."
jupyterhub 
echo "Hub is running..."
