#!/usr/bin/env sh 

echo "Adding proxy port to shared database..."
node update_database.js
echo "Database updated"


echo "Starting proxy server..."
configurable-http-proxy --ip=$PROXY_WEB_URL --port=$PORT --api-ip=$PROXY_WEB_URL --api-port=$PORT --default-target=${HUB_WEB_URL}:${HUB_PORT} --error-target=${HUB_WEB_URL}:${HUB_PORT}/hub/error
echo "Proxy server running..."
